#version: 1.0.1

FROM centos-6.8-base-custom:latest
MAINTAINER   wandapeng "dapeng.wan@pintuibao.cn"
###########配置服务自启动##########
COPY run.sh  /deploy/scripts/
RUN chmod 755 /deploy/scripts/*.sh
ENTRYPOINT ["/deploy/scripts/run.sh"]
###########发布相关端口##########
EXPOSE 22
###########安装##########
RUN mkdir -p /opt/uranus-server/logs/
RUN mkdir -p /opt/uranus-server/config/
WORKDIR /opt/uranus-server/
COPY bin/ /opt/uranus-server/bin/
RUN chmod 755 /opt/uranus-server/bin/*
###############加载经常变化的数据文件进入镜像文件
COPY libs/ /opt/uranus-server/libs/
COPY uranus-server.jar /opt/uranus-server/
###########创建数据卷目录##########
VOLUME    /opt/ /var/log/

